Homework #1
IvanSotenko/DoMyHomework pull request #2
Opened 2022-09-23 16:17 UTC by IvanSotenko

## Сделал второе дз
Реализовал функции для:

- Возведения в степень наивным образом (1)
- Возведения в степень быстрым способом (2)
- Нахождения разницы между наибольшим и наименьшим элементом массива (3)
- Генерации массива с нечётными числами строго между заданными (4)

Также тесты к ним

2022-10-08 15:50 UTC, gsvgit requested changes

2022-10-08 15:50 UTC, gsvgit commented on src/shapito/Main.fs
> -    let assembly = lazy (Assembly.GetEntryAssembly())
А это всё нужно в домашке?

2022-10-08 15:50 UTC, gsvgit commented on src/shapito/Main.fs
> +    let delta (arr: int array) =
А что, разницу только для целых чисел считать можно? А что не так с другими типами?

2022-10-08 15:50 UTC, gsvgit commented on src/shapito/Main.fs
> +            failwith "Empty array"
И что? Обсуждали, как должны выглядеть сообщения об ошибках.

2022-10-08 15:50 UTC, gsvgit commented on src/shapito/Main.fs
>          let parser = ArgumentParser.Create<CLIArguments>(programName = "shapito")
А это как-то в домашке используется?

2022-10-08 15:50 UTC, gsvgit commented on tests/shapito.Tests/Tests.fs
> +                  Expect.equal
Раз уж знаете про ```**```, то что Вам помешало просто свойство протестировать, а не писать всё вот это руками?

2022-10-12 10:51 UTC, IvanSotenko commented on tests/shapito.Tests/Tests.fs
> +                  Expect.equal
Тут проблема, в тестах степеней часто выпадает ошибка:
`Actual value was 289.694486 but had expected it to be 289.694486.`
В том числе в тестах свойств. И это если честно вводит в ступор :(

2022-10-12 12:00 UTC, gsvgit commented on tests/shapito.Tests/Tests.fs
> +                  Expect.equal
Хех. На паре покажете. С ходу --- проблемы с ошибкой при высилении.

2022-10-16 12:25 UTC, IvanSotenko commented
Делаю правки:
- [ ] Убрать лишнее из домашки
- [ ] Добавить тестирование свойств для некоторых функции
- [ ] Изменить сообщение об ошибках
- [ ] Добавить счёт разницы для типа float

2022-10-16 13:36 UTC, closed without merging