Homework #2
IvanSotenko/DoMyHomework pull request #3
Opened 2022-10-12 17:00 UTC by IvanSotenko

В домашке реализовал некоторые функции для типов `MyList` и `MyOOPList`, а именно:
- Конкатенацию
- Сортировку BubbleSort
- Сортировку QuickSort

Также побочно сделал методы для конвертации типов `MyList` и `MyOOPList` в другие типы.

Тесты тоже сделал к этому добру тоже сделал.

2022-10-14 05:38 UTC, gsvgit requested changes
Сперва проверяем, что всё сделано, а потом реквест.

2022-10-14 05:38 UTC, gsvgit commented on src/shapito/Main.fs
>  namespace shapito
И всё же классное пространство имён. Отражает суть происходящего, так сказать.

2022-10-14 05:38 UTC, gsvgit commented on src/shapito/MyList.fs
> +let go () : MyList<int> = map ((+) 1) (Cons(1, Cons(3, Empty)))
А это зачем-то в домашке надо?

2022-10-14 05:38 UTC, gsvgit commented on src/shapito/MyList.fs
> +                separator tail (concat less (Cons(head, Empty))) equal more pivot
Правда ли, что здесь надо добавлять в конец? ```concat``` --- дорогая операция. Если ей можно не пользоваться, то лучше не пользоваться.

2022-10-14 05:38 UTC, gsvgit commented on src/shapito/MyList.fs
> +        | Empty -> concat (concat (quickSort less) equal) (quickSort more)
Оох.. Зачем так-то логику выворачивать.

2022-10-14 05:38 UTC, gsvgit commented on src/shapito/OOPList.fs
> +let rec oopMap (f: IActor<'value, 'result>) (lst: IList<'value>) : IList<'result> =
А это тут надо?

2022-10-14 05:38 UTC, gsvgit commented on src/shapito/OOPList.fs
> +let go2 () : IList<int> =
И это?

2022-10-14 05:38 UTC, gsvgit commented on src/shapito/OOPList.fs
> +        | _ -> failwith "isSorted can only handle NonEmptyList and EmptyList"
А получил кого? Почему бы об этом не сообщить?

2022-10-14 05:38 UTC, gsvgit commented on src/shapito/OOPList.fs
> +        | _ -> failwith "separator can only handle NonEmptyList and EmptyList"
Те же вопросы про вывернутую логику и про сообщение об ошибке.

2022-10-14 05:38 UTC, gsvgit commented on src/shapito/Say.fs
> +module Say =
А зачем это в домашке?

2022-10-14 05:38 UTC, gsvgit commented on src/shapito/Translator.fs
> +﻿module shapito.Translator
Посмотрите на сисемтне модули ```List``` и ```Array``` и на то, как в них функции конвертации называются.

2022-10-14 05:38 UTC, gsvgit commented on src/shapito/Translator.fs
> +            Cons(arr[i], (SubArrToMyList(i + 1) arr))
Чот тут сервер ругается. похоже, он прав.

2022-10-14 05:38 UTC, gsvgit commented on tests/shapito.Tests/linkedListsTests.fs
> +                  MyListToList(MyList.concat (lst1 |> listToMyList) (lst2 |> listToMyList))
И что у Вас так стили имён скачут?

2022-10-14 05:38 UTC, gsvgit commented on tests/shapito.Tests/linkedListsTests.fs
> +          <| fun (lst: list<int>) ->
А кроме интов и строк бывают ещё типы?

2022-10-18 19:31 UTC, IvanSotenko commented on src/shapito/Translator.fs
> +﻿module shapito.Translator
Я посмотрел, там эти функции находятся внутри самих модулях (`List.toArray`). Попытался так же сделать с `MyList` и `OOPList`, но компиляционная последовательность не позволяет, если `OOPList `стоит перед `MyList`, то `MyList` не знает что такое `OOPList`. Так наверно это в условиях одного проекта не сделать?

2022-10-21 05:06 UTC, gsvgit requested changes
Попробуйте настроить себе https://fsprojects.github.io/FSharpLint/ в CI. Глядишь, он будет автоматом отлавливать всякие проблемы с именами и т.д.

2022-10-21 05:06 UTC, gsvgit commented on tests/shapito.Tests/shapito.Tests.fsproj
> +        <Compile Include="linkedListsTests.fs" />
А вот файлы лучше с заглавной называть.

2022-10-21 05:06 UTC, gsvgit commented on tests/shapito.Tests/linkedListsTests.fs
> +﻿module DoMyHomework.Tests.linkedListsTests
Модули лучше с заглавной называть.

2022-10-21 16:24 UTC, IvanSotenko commented
### Делаю правки (2)

- [ ] Разобраться со стилями имён
- [ ] Улучшить функцию `isSorted` _(Упражнение)_

2022-10-21 17:03 UTC, IvanSotenko commented on src/shapito/MyList.fs
> +let rec concat (list1: MyList<'value>) (list2: MyList<'value>) : MyList<'value> =
Мой ход мыслей был в том, что типы `MyList`, `OOPList`, `Array`, `List` сами начинаются с больших букв, поэтому показалось, что писать `myListToOOPList` было бы некруто.

2022-10-24 06:01 UTC, gsvgit commented
Разрулите, пожалуйста, конфликты с основной веткой.

2022-10-26 06:36 UTC, gsvgit requested changes

2022-10-26 06:36 UTC, gsvgit commented on src/shapito/MyList.fs
> +let rec concat (list1: MyList<'value>) (list2: MyList<'value>) : MyList<'value> =
Ну ладно. Настроете FSharpLint --- узнаете много нового и интересного.  В любом случае, такой подход к именованию не самый правильный.

2022-10-26 06:36 UTC, gsvgit commented on tests/shapito.Tests/LinkedListsTests.fs
> +          testProperty "(MyList.concat list1 list2) is (list1 @ list2)"
А ещё для конкатенации можно провеить, что она длины сохраняет: сумма длин входных равна длине результата.

2022-10-26 06:36 UTC, gsvgit commented on src/shapito/MyList.fs
> +    let rec divideAndApplyQuickSort list less equal more pivot =
Всё ещё всё в одну кучу. Учитесь разделять логику. Так потом проще понимать, что же тут было написано.

2022-10-26 16:29 UTC, IvanSotenko commented
### Делаю правки (3)

- [x] Прогнать код через FSharpLint
- [x] Добавить свойство для тестирования `concat`
- [x] Исправить логику `quickSort`

2022-10-27 06:05 UTC, gsvgit reviewed
В целом ок. Осталось отделить предыдущую домашку от текущей.

2022-10-27 06:05 UTC, gsvgit commented on src/shapito/Homework1.fs
> +﻿module DoMyHomework.Homework1
Хех. Я, кажется, несколько раз говорил, что рефакторинг предыдущих домашек не имеет к текущей домашке никакого отношения. Эти правки должны идти отдельно и мне их можно не показывать. 

Но я рад, что Вы совладали с FSharpLint.

2022-10-27 07:54 UTC, IvanSotenko commented
> В целом ок. Осталось отделить предыдущую домашку от текущей.
@gsvgit
Не очень понял, если честно. То есть просто удалить всё, что вмёржилось от предыдущей домашки?

2022-10-27 08:29 UTC, gsvgit commented
> > В целом ок. Осталось отделить предыдущую домашку от текущей.
> 
> @gsvgit Не очень понял, если честно. То есть просто удалить всё, что вмёржилось от предыдущей домашки?

Ну как удалить. Изменения должны попасть в основную ветку. Но в этом реавесте их быть не должно.

2022-10-27 16:03 UTC, gsvgit requested changes

2022-10-27 16:03 UTC, gsvgit commented on src/shapito/MyList.fs
> +                isSorted (Cons(value2, tail))
Это, конечно, лучше, чем if x = true, но все же.

2022-10-27 16:03 UTC, gsvgit commented on src/shapito/OOPList.fs
> +            list.Tail :? EmptyList<'Value>
Гы. А здесь нормально. Вы точно сами над кодом работаете?

2022-10-27 18:35 UTC, gsvgit commented on src/shapito/OOPList.fs
> +            list.Tail :? EmptyList<'Value>
Которую из двух?)

2022-10-27 18:37 UTC, gsvgit approved these changes
Пойдет!

2022-10-27 19:04 UTC, IvanSotenko commented
`Подошла к концу эпоха...`

2022-10-27 19:04 UTC, merged