Homework #1
IvanSotenko/DoMyHomework pull request #4
Opened 2022-10-16 13:48 UTC by IvanSotenko

Я переименовал ветку для домашнего задания номер 1, поэтому пришлось закрыть #2 и создать этот PR.
### Последние правки
- [ ] Убрал лишнее из домашки
- [ ] Добавил тестирование свойств для некоторых функции
- [ ] Изменил сообщение об ошибке в функции для функции `Homework1.delta`
- [ ] Добавить счёт разницы для различных типов данных в функции `Homework1.delta`

2022-10-16 14:13 UTC, IvanSotenko commented
Что ж, сначала убедиться, что всё в порядке, и только потом просить ревью. Урок получен. Но почему не получался именно `build (windows-latest) (pull_request)`, я так и не понял ¯\_(ツ)_/¯.

2022-10-17 05:45 UTC, gsvgit requested changes

2022-10-17 05:45 UTC, gsvgit commented on src/shapito/Main.fs
> +    let rec silly_pow_rec (bas: float) (power: uint) =
А откуда тут снова что-то про степень?

2022-10-17 05:45 UTC, gsvgit commented on tests/shapito.Tests/Homework1Tests.fs
> +                      (System.Double.IsNaN actualResult)
Тут что-то не так. Если ожидаемый NaN, то и полученный должен быть NaN.

2022-10-17 05:45 UTC, gsvgit commented on tests/shapito.Tests/Homework1Tests.fs
> +                      (System.Double.IsNaN actualResult)
И тут тоже. Копипаста?

2022-10-17 05:45 UTC, gsvgit commented on tests/shapito.Tests/Homework1Tests.fs
> +                      (System.Double.IsNaN actualResult)
И снова.

2022-10-17 11:11 UTC, IvanSotenko commented on src/shapito/Main.fs
> +    let rec silly_pow_rec (bas: float) (power: uint) =
У меня там просто две функции для первого задания, одна с использованием мутабельных переменных, а другая с рекурсией

2022-10-18 05:41 UTC, gsvgit reviewed
И всё же я не понимаю, почему у Вас два файла в которых что-то про степени: Homework1.fs и Main.fs Мне всё же кажктся, что что-то тут не так.

2022-10-18 10:26 UTC, IvanSotenko commented
> И всё же я не понимаю, почему у Вас два файла в которых что-то про степени: Homework1.fs и Main.fs Мне всё же кажктся, что что-то тут не так.

Да, действительно, я не что-то заметил...

2022-10-18 11:00 UTC, gsvgit approved these changes
Пойдёт!

2022-10-18 11:00 UTC, gsvgit commented
Ха, ну, теперь решайте конфликты.

2022-10-18 11:02 UTC, IvanSotenko commented
Я знал, что когда-нибудь этот день настанет! :)

2022-10-18 11:35 UTC, merged