Homework #4
IvanSotenko/DoMyHomework pull request #6
Opened 2022-12-07 12:09 UTC by IvanSotenko

### Домашка 4

- Реализовал типы `Vector` и `Matrix`, предназначенные для хранения разреженных векторов и матриц. Типы реализованы на базе типов `BinTree` и `QTree`. Чтобы не хранить лишней информации, реализована функция схлопывания листьев деревьев, которая срабатывает в том числе при инициализации объектов вектора и матрицы.
- Реализована рекурсивная функция векторно-матричного умножения для типов `Vector` и `Matrix`, без использования обращения по индексу.
- И тесты на всё это добро.

2022-12-07 12:19 UTC, gsvgit commented on src/shapito/Matrix.fs
> +        let collapsed = Node (collapse nw, collapse ne, collapse sw, collapse se)
А зачем Вы конструируете узел только для того, чтобы на следующей же строке его разобрать на куски?

2022-12-07 12:19 UTC, gsvgit commented on src/shapito/Matrix.fs
> +    member this.getItem (row, column) =
Можно красивее: https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/members/indexed-properties

2022-12-07 12:19 UTC, gsvgit commented on src/shapito/Multiply.fs
> +
Думаю, даже наивную лучше сразу делать так, чтобы матрица и вектор могли быть разных типов. Для тестирования пригодиться, как минимум.

2022-12-07 12:19 UTC, gsvgit commented on src/shapito/Multiply.fs
> +let naiveMultiply (vec: Vector<'A>) (mat: Matrix<'A>) (add: 'A -> 'A -> 'A) (multiply: 'A -> 'A -> 'A) =
И функции я бы рекомендовал сразу делать для option, чтобы ниже отдельно их не оборачивать.

2022-12-10 17:42 UTC, gsvgit requested changes

2022-12-10 17:42 UTC, gsvgit commented on src/shapito/BinTree.fs
> +    | Node of leftKid: BinTree<'Value> * rightKid: BinTree<'Value>
Традиционно они Child

2022-12-10 17:42 UTC, gsvgit commented on src/shapito/BinTree.fs
> +    let rec treePlusSub tree1 tree2 =
Я правильно понимаю, что в сложении Вы не проверяете, что результат может сожержать поддеревья из None-ов? Не надо так.

2022-12-10 17:42 UTC, gsvgit commented on src/shapito/BinTree.fs
> +let rec collapseBinTree tree =
Такая функция --- отдельный проход по дереву. Лучше сворачивать сразу.

2022-12-10 17:42 UTC, gsvgit commented on src/shapito/Matrix.fs
> +let constructQTree (bas: Option<'A> [,]) =
`bas` --- не очень говорящее название.

2022-12-10 17:42 UTC, gsvgit commented on src/shapito/Multiply.fs
> +    let plus a b =
Разберитесь всё же с Option. Вы так, напрмиер, маску нормально вряд ли выразите. Особенно комплементарную.

2022-12-10 17:42 UTC, gsvgit commented on src/shapito/Multiply.fs
> +        | Some x, Some y -> Some(multiply x y)
А что, если в результате вычислений получился кто-то, кого я не хочу хранить?

2022-12-10 17:42 UTC, gsvgit commented on src/shapito/Multiply.fs
> +        | Some x, Some y -> Some(add x y)
А что, если в результате вычислений получился кто-то, кого я не хочу хранить?

2022-12-10 17:42 UTC, gsvgit commented on src/shapito/QTree.fs
> +let rec collapseQTree tree =
Ну тут тоже. Сворачивать отдельным проходом --- злодейство.

2022-12-10 17:42 UTC, gsvgit commented on tests/shapito.Tests/MatrixOperationsTests.fs
> +let vectorTypeTests =
А что на поэлементную операцию не добавили сразу тестов?

2022-12-10 18:20 UTC, IvanSotenko commented on src/shapito/Multiply.fs
> +    let plus a b =
Вы имеете ввиду 
`(add: Option<'C> -> Option<'C> -> Option<'C>)` 
и 
`(multiply:  Option<'A> -> Option<'B> -> Option<'C>) `?

2022-12-14 06:34 UTC, gsvgit commented on src/shapito/Matrix.fs
> +let constructQTree2 (basis: Option<'A> [,]) =
А потом будет 3, 4 ... Что тут происходит?

2022-12-14 06:34 UTC, gsvgit commented on src/shapito/Vector.fs
> +let constructBinTree2 (basis: array<Option<'A>>) =
И снова что-то странное с именами

2022-12-14 13:35 UTC, gsvgit approved these changes

2022-12-14 14:51 UTC, merged