Homework #5
IvanSotenko/DoMyHomework pull request #7
Opened 2022-12-25 09:00 UTC by IvanSotenko

В процессе. Осталось сделать только тесты (наивная функция BFS уже готова).

2022-12-26 08:10 UTC, gsvgit reviewed
Внимательно постмотрите на то, что у Вас снаружи должны быть только операции над векторами и матрицами. Никаких деревьев.

2022-12-26 08:10 UTC, gsvgit commented on src/shapito/BFS.fs
> +    | Some x, _ -> Some x
Это можно чуть короче записать: 
```
| Some x, Some _ | Some _, Some x -> Some x 
```

2022-12-26 08:10 UTC, gsvgit commented on src/shapito/BFS.fs
> +    | Some x, Some _ -> Some x
И тут тоже можно компактнее.

2022-12-26 08:10 UTC, gsvgit commented on src/shapito/BFS.fs
> +    Vector((addBinTree front.Data result.Data frontMask), front.Length)
А почему не просто операции над векторами? Зачем через деревья всё явно гонять?

2022-12-26 11:00 UTC, gsvgit commented on src/shapito/BFS.fs
> +    | Some x, None -> Some x
Похоже, что тут вообще одной строкой можно. Вам же все равно, как выглядит второй элемент.

2022-12-27 08:29 UTC, gsvgit requested changes

2022-12-27 08:29 UTC, gsvgit commented on src/shapito/BFS.fs
> +let updateFront (front: Vector<Marker>) (result: Vector<uint>) = vectorize frontMask front result
Всё ещё какая-то магия немного. У Вас просто должна быть обычная поэлементная операция над двумя векторами.

2022-12-27 08:29 UTC, gsvgit commented on src/shapito/BFS.fs
> +let updateFront (front: Vector<Marker>) (result: Vector<uint>) = vectorize frontMask front result
Да и зачем ещё обёртки делать --- не понятно. Прям на месте в BFS применили правильную поэлементную операцию и всё.

2022-12-27 08:29 UTC, gsvgit commented on src/shapito/BFS.fs
> +        // we multiply the vector by the matrix and apply a "mask" to it
Содержательность комментария зашкаливает.

2022-12-27 08:29 UTC, gsvgit commented on src/shapito/Vector.fs
> +let uintListToVector (verts: list<uint>) (length: int) (value: 'A) =
Что? А если у меня будет списов байт или ещё чего? На каждый тип будете городить подобную функцию? Подумайте, как это можно выразить нормально через другие.

2022-12-27 08:29 UTC, gsvgit commented on src/shapito/Vector.fs
> +    new(verts: List<uint>, length, value) =
Больше конструкторов богу конструкторов! Даёшь конструкторы на все случаи жизни!

2022-12-27 10:07 UTC, IvanSotenko commented on src/shapito/Vector.fs
> +let uintListToVector (verts: list<uint>) (length: int) (value: 'A) =
Я думал как-нибудь выразить это дело через один из двух других конструкторов, преобразуя list<uint> в другие структуры, но на это кажется нужно будет тратить лишний обход. 

Тогда я сделаю так, чтобы мы конструктору давали список, и говорили как из элементов этого списка получить координату, а как значение. Такое будет похоже на правду?)

2022-12-27 10:31 UTC, gsvgit commented on src/shapito/Vector.fs
> +let uintListToVector (verts: list<uint>) (length: int) (value: 'A) =
Посмотрите для начала на всякие функции конструирования обычных массивов в F#. Всякие init, create и прочее. Возможно натолкнёт на некоторые мысли.

2022-12-27 17:55 UTC, gsvgit commented on src/shapito/BFS.fs
> +        let newFront = vectorize frontMask (vecMatMultiply front adjMat add mult) result
Что за странное название ```vectorize``` ?

2022-12-27 17:55 UTC, gsvgit commented on src/shapito/BinTree.fs
> +let ofVertList (verts: list<int * 'A>) (length: int) =
И всё же странно. Если у Вас есть нормальный init, то пусть им все снаружи и пользуются. Зачем именно в векторе разные функции на все случаи жизни?

2022-12-27 18:35 UTC, IvanSotenko commented on src/shapito/BFS.fs
> +        let newFront = vectorize frontMask (vecMatMultiply front adjMat add mult) result
Не мог найти подходящее название. А NumPy есть похожая функция, которая так называется.

2022-12-27 20:31 UTC, gsvgit commented on src/shapito/BFS.fs
> +        let newFront = vectorize frontMask (vecMatMultiply front adjMat add mult) result
А я ведь даже говорил и, кажется, в общий чат к писал, какие аналоги есть в F# и на что ориентироваться.

2022-12-27 20:34 UTC, gsvgit commented on src/shapito/BFS.fs
> +        let newFront = vectorize frontMask (vecMatMultiply front adjMat add mult) result
Ну и нумпаевский vectorize про другое совсем.

2022-12-28 07:11 UTC, gsvgit approved these changes

2022-12-28 09:53 UTC, IvanSotenko commented
![images](https://user-images.githubusercontent.com/113289845/209793449-cfd0b4a3-78de-48d7-9b8b-be9b58b0aa23.jpg)

2022-12-28 09:53 UTC, merged